### ISSUE TITLE
ansible version?

### ISSUE THREAD

**Issue by bhandeland** [tomoliveri/ansible_aio_ee#1]
Thank you for building this.  Its a great tool and it clarifies a few issues I was unclear of with ansible-builder.  However, I have one question.

Where does it specify the ansible version to install in the EE?

Thanks,
Brandon

**Comment by tomoliveri** [comment]
Hey Brandon, 

It's on Ansible core 2.11.4rc1

Now included in the readme 👍 

Or do you mean which Ansible version you need in order to use this EE? 
You'd need AWX 17+ / Automation Platform 2.0+

**Comment by bhandeland** [comment]
Thank you!  This is great stuff here.  When running AWX 19.2.0, I've noticed that its running a dev build of ansible 2.12.  Do you have any recommendations on how to control  the ansible version itself?

**Comment by tomoliveri** [comment]
I'm afraid we're at the mercy of the ansible-builder project. 
I can't see an easy way to specify the Ansible version when rebuilding the image. Might have to change it after the image is built, and save that new, custom version. 

Not ideal, but definitely worth a feature request - https://github.com/ansible/ansible-builder/
