### ISSUE TITLE
Hashi_vault issue

### ISSUE THREAD

**Issue by chirogocki** [tomoliveri/ansible_aio_ee#2]
Hi,

Thanks for your great job. I'm just trying to use your EE  with hashi_vault community module but it fails :

`"An unhandled exception occurred while running the lookup plugin 'community.hashi_vault.hashi_vault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Please pip install hvac to use the hashi_vault lookup module."`

I don't understand the problem, you seem to take care of dependencies here for this particular module :https://github.com/tomoliveri/ansible_aio_ee/blob/main/collection_requirements/community.hashi_vault.txt 

Can you help me please ?

**Comment by tomoliveri** [comment]
Hi,

Absolutely. Thank you for raising this, Hashicorp Vault is definitely an
essential one.

I've added those dependencies and am rebuilding the execution environment
now.

If all goes well I'll have it pushed in an hour or so.

**Comment by tomoliveri** [comment]
hvac module added, hashicorp_vault should work now.
