### ISSUE TITLE
Having some problem using netbox with this EE

### ISSUE THREAD

**Issue by JoakimNordin** [tomoliveri/ansible_aio_ee#4]
I'm trying to use your EE for nb_lookup against netbox as I'm hoping not to have to build a WW myself, as I jsut want to test it out. But I get this error in AWX when I use this EE: `"msg": "An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <class 'ansible.errors.AnsibleError'>, original message: pynetbox must be installed to use this plugin"`

Seems you do include pynetbox as a requirement for netbox plugin though, so I'm not sure why it's complaining. Do you get the same error?

Here's the playbook I'm using.

`- hosts: localhost
  gather_facts: no
  collections:
   - netbox.netbox
  connection: local

  tasks:
    # query a list of devices
    - name: Obtain list of devices from NetBox
      debug:
        msg: >
          "Device {{ item.value.display_name }} (ID: {{ item.key }}) was
           manufactured by {{ item.value.device_type.manufacturer.name }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
                      api_endpoint='{{ NETBOX_API }}',
                      token='{{ NETBOX_TOKEN }}') }}"`

NETBOX_API = the URL to netbox.
NETBOX_TOKE = a read only api token, as I just want to query.

**Comment by tomoliveri** [comment]
Hey!

Sorry for the slow reply. I've added the pynetbox module, so this should now work. 

Let me know if you have any trouble.
