### ISSUE TITLE
EE error

### ISSUE THREAD

**Issue by mattiaoui** [tomoliveri/ansible_aio_ee#5]
Hi,

i download your docker image and configure the new EE on my Ansible Automation (vmware in this case), but when job running terminate with this error:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'urllib3.packages.six'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (requests) on automation-job-376-bvdkd's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
.

thanks
mattia

**Comment by tomoliveri** [comment]
Hey Mattia, 

Thanks for letting me know it was missing ulrlib3. 

I'm adding that in now and rebuilding. 
Generally I have a lot of trouble getting additional modules in as we hit the container size limit. Fingers crossed this one is small enough to squeeze in. 

I'll try to have this sorted in the next 12 hours.

**Comment by mattiaoui** [comment]
thanks, i test to create my ee for testing, if i set ulrlib3 on requirement.txt file and recreate image, are sufficient?

**Comment by tomoliveri** [comment]
Yep, that should do it. And if you get an error about it running out of space, select one (or more) from requirements.txt to disable... Any you suspect you won't need. 

I'd recommend removing; logstash,redis,memcache,LogDNA & linode_api4

**Comment by tomoliveri** [comment]
urllib3 has been added.
